[Icon Theme]
Name=Oxygen
DisplayDepth=32
Inherits=default
Example=folder
LinkOverlay=link
LockOverlay=lockoverlay
ShareOverlay=share
ZipOverlay=zip
DesktopDefault=48
DesktopSizes=32,48
ToolbarDefault=22
ToolbarSizes=22,32,48
MainToolbarDefault=22
MainToolbarSizes=22,32,48
SmallDefault=22
SmallSizes=22,32,48
PanelDefault=32
PanelSizes=22,32,48
DialogDefault=32
DialogSizes=22,32,48

Directories=22x22,32x32,48x48

[22x22]
Size=22

[32x32]
Size=32

[48x48]
Size=48